services:
  appointment-mysql:
    image: 'mysql:latest'
    container_name: mysql-appointment-service-dev
    environment:
      - 'MYSQL_DATABASE=appointment_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3310:3306'