services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-billing-service-dev
    environment:
      - 'MYSQL_DATABASE=billing_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3311:3306'
