services:
  medicine-mysql:
    image: 'mysql:latest'
    container_name: mysql-medicine-service-dev
    environment:
      - 'MYSQL_DATABASE=medicine_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
