services:
  auth-mysql:
    image: 'mysql:latest'
    container_name: mysql-auth-service-dev
    environment:
      - 'MYSQL_DATABASE=auth_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'