services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-hr-service-dev
    environment:
      - 'MYSQL_DATABASE=hr_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3309:3306'